import { useState } from 'react'
import { Clock3, Database, Filter } from 'lucide-react'
import type { OperationsData } from '../types/operations'
import { riskLevel } from '../utils/formatters'

export function CrowdHeatMap({ data }: { data: OperationsData }) {
  const [park, setPark] = useState('All parks')
  const [level, setLevel] = useState('all')
  const parkId = data.parks.find((item) => item.name === park)?.id
  const zones = data.crowdZones.filter((zone) => (park === 'All parks' || zone.parkId === parkId) && (level === 'all' || riskLevel(zone.pressureScore) === level))
  return <div className="content-screen"><div className="screen-heading"><div><span className="eyebrow">FABRIC SQL · CROWDZONES</span><h2>Crowd Pressure Network</h2><p>Persisted zone scores queried directly from the CrowdZones table.</p></div><div className="filters"><Filter size={16}/><select value={park} onChange={(event) => setPark(event.target.value)}><option>All parks</option>{data.parks.map((item) => <option key={item.id}>{item.name}</option>)}</select><select><option>Current database state</option></select><select value={level} onChange={(event) => setLevel(event.target.value)}><option value="all">All levels</option><option value="low">Low</option><option value="medium">Moderate</option><option value="high">High</option><option value="critical">Critical</option></select></div></div><div className="crowd-layout"><section className="crowd-map"><div className="grid-lines"/>{data.parks.map((item, parkIndex) => <div className={`stylized-park park-${parkIndex}`} key={item.id}><header><strong>{item.name}</strong><span>{item.guestDensity}</span></header><div className="zone-grid">{zones.filter((zone) => zone.parkId === item.id).map((zone, index) => { const risk = riskLevel(zone.pressureScore); return <div key={zone.id} className={`heat-cell ${risk}`} style={{ animationDelay: `${index * 80}ms` }}><strong>{zone.pressureScore}</strong><small>{zone.name}</small></div> })}</div></div>)}</section><aside className="crowd-rail"><h3>Pressure leaders</h3>{[...zones].sort((left, right) => right.pressureScore - left.pressureScore).slice(0, 6).map((zone, index) => <div className="rank-row" key={zone.id}><b>{String(index + 1).padStart(2, '0')}</b><span><strong>{zone.name}</strong><small>{data.parks.find((item) => item.id === zone.parkId)?.name}</small></span><em className={riskLevel(zone.pressureScore)}>{zone.pressureScore}</em></div>)}<div className="sim-note"><Database size={16}/><span><strong>Database sourced</strong><small>No client-side crowd simulation.</small></span></div><div className="sim-note"><Clock3 size={16}/><span><strong>Refresh cadence</strong><small>Repository snapshot every 30 seconds.</small></span></div></aside></div></div>
}
