import { useState } from 'react'
import { AlertTriangle, CalendarClock, Settings2, Thermometer, Waves } from 'lucide-react'
import type { OperationsData, RideTelemetry } from '../types/operations'
import { riskLevel } from '../utils/formatters'

export function PredictiveMaintenance({ data }: { data: OperationsData }) {
  const assets = [...data.rideTelemetry].sort((left, right) => right.predictedFailureRisk - left.predictedFailureRisk)
  const [selected, setSelected] = useState<RideTelemetry>(assets[0])
  const health = Math.round(100 - assets.reduce((sum, item) => sum + item.predictedFailureRisk, 0) / Math.max(1, assets.length))
  return <div className="content-screen"><div className="screen-heading"><div><span className="eyebrow">FABRIC SQL TELEMETRY</span><h2>Predictive Maintenance</h2><p>Persisted ride telemetry joined with maintenance asset records.</p></div><span className="simulated-pill">DATABASE LIVE</span></div><div className="maintenance-layout"><aside className="asset-health"><div className="gauge" style={{ '--score': `${health * 1.8}deg` } as React.CSSProperties}><div><strong>{health}</strong><small>Asset health</small></div></div><h3>Fleet health score</h3><p>{assets.filter((asset) => asset.predictedFailureRisk >= 70).length} assets need elevated monitoring.</p><div className="alert-examples"><span><Waves/>Vibration telemetry</span><span><Thermometer/>Motor temperature</span><span><AlertTriangle/>Downtime events</span><span><CalendarClock/>Maintenance schedule</span></div></aside><section className="asset-table"><table><thead><tr><th>Asset</th><th>Risk</th><th>Temp</th><th>Vibration</th><th>Cycles</th><th>Action</th></tr></thead><tbody>{assets.map((asset) => <tr key={asset.rideId} className={selected?.rideId === asset.rideId ? 'selected' : ''} onClick={() => setSelected(asset)}><td><strong>{asset.rideName}</strong><small>{asset.assetType} · {asset.park}</small></td><td><span className={`risk-chip ${riskLevel(asset.predictedFailureRisk)}`}>{asset.predictedFailureRisk}%</span></td><td>{asset.motorTemperature}°C</td><td>{asset.vibrationScore}</td><td>{asset.cycleCountToday}</td><td>{asset.recommendedAction}</td></tr>)}</tbody></table></section>{selected && <aside className="maintenance-detail"><Settings2 size={20}/><span className="eyebrow">ASSET TWIN</span><h2>{selected.rideName}</h2><p>{selected.land} · {selected.assetType}</p><div className={`failure-score ${riskLevel(selected.predictedFailureRisk)}`}><strong>{selected.predictedFailureRisk}%</strong><span>Maintenance<br/>risk score</span></div><dl><div><dt>Last inspection</dt><dd>{new Date(selected.lastInspectionDate).toLocaleDateString()}</dd></div><div><dt>Next maintenance</dt><dd>{new Date(selected.nextPlannedMaintenance).toLocaleDateString()}</dd></div><div><dt>Recommended action</dt><dd>{selected.recommendedAction}</dd></div><div><dt>Fault code</dt><dd>{selected.faultCode ?? 'No active fault'}</dd></div></dl></aside>}</div></div>
}
